package main

const  (
	TYPE_EVENT = 1
	TYPE_PROCESS_CREATE = 2
	TYPE_PROCESS_TERMINATE = 3
	TYPE_FILE_CREATION_TIME = 4
	TYPE_NETWORK_CONNECTION = 5
	TYPE_DRIVER_LOADED = 6
	TYPE_IMAGE_LOADED = 7
	TYPE_RAW_ACCESS_READ = 8
	TYPE_CREATE_REMOTE_THREAD = 9
)

const (
	SUMMARY_TYPE_PROCESS_CREATE_PATH_SHA256_GROUP_PATH_ORDER_PATH = 1
	SUMMARY_TYPE_PROCESS_CREATE_PATH_SHA256_GROUP_PATH_ORDER_HASH = 2
	SUMMARY_TYPE_PROCESS_CREATE_PATH_MD5_GROUP_PATH_ORDER_PATH = 3
	SUMMARY_TYPE_PROCESS_CREATE_PATH_MD5_GROUP_PATH_ORDER_HASH = 4
	SUMMARY_TYPE_DRIVER_LOADED_PATH_SHA256_GROUP_PATH_ORDER_PATH = 5
	SUMMARY_TYPE_DRIVER_LOADED_PATH_SHA256_GROUP_PATH_ORDER_HASH = 6
	SUMMARY_TYPE_DRIVER_LOADED_PATH_MD5_GROUP_PATH_ORDER_PATH = 7
	SUMMARY_TYPE_DRIVER_LOADED_PATH_MD5_GROUP_PATH_ORDER_HASH = 8

	SUMMARY_TYPE_IMAGE_LOADED_PATH_SHA256_GROUP_PATH_ORDER_PATH = 9
	SUMMARY_TYPE_IMAGE_LOADED_PATH_SHA256_GROUP_PATH_ORDER_HASH = 10
	SUMMARY_TYPE_IMAGE_LOADED_PATH_MD5_GROUP_PATH_ORDER_PATH = 11
	SUMMARY_TYPE_IMAGE_LOADED_PATH_MD5_GROUP_PATH_ORDER_HASH = 12

	SUMMARY_TYPE_NETWORK_CONNECTION_DISTINCT_DEST_IP = 13
	SUMMARY_TYPE_NETWORK_CONNECTION_DISTINCT_DEST_IP_COUNT = 14

	SUMMARY_TYPE_NETWORK_CONNECTION_DISTINCT_DEST_HOST = 15
	SUMMARY_TYPE_NETWORK_CONNECTION_DISTINCT_DEST_HOST_COUNT = 16
)