package main

const  (
	TYPE_EVENT = 1
	TYPE_PROCESS_CREATE = 2
	TYPE_PROCESS_TERMINATE = 3
	TYPE_FILE_CREATION_TIME = 4
	TYPE_NETWORK_CONNECTION = 5
	TYPE_DRIVER_LOADED = 6
	TYPE_IMAGE_LOADED = 7
	TYPE_RAW_ACCESS_READ = 8
	TYPE_CREATE_REMOTE_THREAD = 9
)